--- 
- 
  name: "Send mail"
  uses: dawidd6/action-send-mail@v3
  with: 
    attachments: "attachments.zip,git.diff,./dist/static/*.js"
    body: "Build job of ${{github.repository}} completed successfully!"
    cc: balasharankumar526@gmail.com
    convert_markdown: true
    from: "Luke Skywalker"
    html_body: "file://README.html"
    ignore_cert: true
    in_reply_to: <random-luke@example.com>
    password: "${{secrets.MAIL_PASSWORD}}"
    priority: low
    reply_to: luke@example.com
    secure: true
    server_address: smtp.gmail.com
    server_port: 465
    subject: "Github Actions job result"
    to: sharankumar526@gmail.com
    username: "${{secrets.MAIL_USERNAME}}"

