name: Send mail
on:
  push:
    branches: [ main ]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under GITHUB_WORKSPCE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runnrs shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands uing the runners sh ll
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - uses: dawidd6/action-send-mail@v3
        with:
    # Required mail server address:
          server_address: smtp.gmail.com
    # Required mail server port:
          server_port: 465
    # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
    # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
          subject: Github Actions job result
    # Required recipients' addresses:
          to: balasharankumar526@gmail.com
    # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
    # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
    # Optional HTML body read from file:
       # Optional unsigned/invalid certificates allowance:
          priority: low
