name: Notifications
on:
  push:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: send mail
      
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
          subject: Github Actions job result
    # Required recipients' addresses:
          to: sharankumar526@gmail.com
    # Required sender full name (address can be skipped):
          from: BALA # <user@example.com>
    # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
